---
- name: kanthaus-nextcloud | setup
  hosts: all
  become: yes
  vars_files:
    - secrets.vars.yml
  vars:
    site: kanthaus-nextcloud
    server_name: cloud.kanthaus.online
    redirects: []
    postgresql_user: kanthaus-nextcloud
    postgresql_database: kanthaus-nextcloud
    postgresql_socket_auth: false
    nextcloud_apps: []

  tasks:
    - name: check ansible version
      include_role:
        name: check-ansible-version

    - name: basic-site
      include_role:
        name: basic-site
      tags:
        - nginx
        - cert

    - name: php-fpm-site
      include_role:
        name: php-fpm-site
      vars:
        memory_limit: '512M'

    - name: postgresql-db
      include_role:
        name: postgresql-db
      vars:
        # backup_host: tor-relay.chandi.it
        # backup_user: tiltec
        # backup_path: ~/kanthaus-nextcloud-backup/
        # backup_password set by secrets.vars.yml

    - name: nextcloud
      include_role:
        name: nextcloud
      vars:
        nextcloud_webroot: "/var/www/{{ site }}/www"
        nextcloud_data_dir: "/var/www/{{ site }}/nextcloud_data"
        nextcloud_admin_user: admin
        nextcloud_trusted_domains:
          - "{{ server_name }}"
        # nextcloud_admin_password set by secrets.vars.yml

