---

- git:
    repo: https://github.com/discourse/discourse_docker.git
    dest: '{{ discourse_location }}'
    update: yes

- name: bootstrap discourse
  command: ./launcher bootstrap web_only
  args:
    chdir: "{{ discourse_location }}"

- name: destroy existing discourse container
  command: ./launcher destroy web_only
  args:
    chdir: "{{ discourse_location }}"
  ignore_errors: true

- name: start new discourse container
  command: ./launcher start web_only
  args:
    chdir: "{{ discourse_location }}"