---
- name: karrot.world | deploy
  hosts: all
  become: yes
  tasks:
    - ansible.builtin.fail:
        msg: Production site needs to be updated to use podman setup
      tags:
        - always

    - name: check ansible version
      include_role:
        name: check-ansible-version

    - name: deploy
      include_role:
        name: karrot-backend-deploy
      vars:
        site: karrot-world
        branch: production