---

- become_user: "{{ site }}-deploy"
  block:

  - name: install tools
    pip:
      name: "{{ item }}"
      virtualenv: "/var/www/{{ site }}/www/backend/env"
    with_items:
      - setuptools
      - pip-tools

  - name: update code
    git:
      repo: https://github.com/yunity/karrot-backend.git
      dest: /var/www/{{ site }}/www/backend
      update: yes
      force: yes
      version: "{{ branch }}"

  - name: pip sync
    command: env/bin/pip-sync
    args:
      chdir: "/var/www/{{ site }}/www/backend"
    changed_when: False

  - name: install mjml dependencies
    command: yarn
    args:
      chdir: "/var/www/{{ site }}/www/backend/mjml"
    changed_when: False

  - name: compile mjml templates
    shell: ./convert
    args:
      chdir: "/var/www/{{ site }}/www/backend/mjml"
    changed_when: False

  - name: manage.py stuff
    command: "env/bin/python manage.py {{ item }}"
    args:
      chdir: "/var/www/{{ site }}/www/backend"
    with_items:
      - check --deploy
      - migrate
      - collectstatic --clear --no-input
      - compilemessages
    changed_when: False

  - name: setup sparkpost account
    command: "env/bin/python manage.py setup_sparkpost --quiet"
    args:
      chdir: "/var/www/{{ site }}/www/backend"
    changed_when: False
    when: not we_are_in_vagrant

    # need to use 'sudo' to allow privileges just for this command
  - name: restart daphne
    shell: "sudo systemctl restart {{ site }}.target"
    changed_when: False

  - name: restart huey
    shell: "sudo systemctl restart {{ site }}-huey.service"
    changed_when: False