---

- become_user: "{{ site }}-deploy"
  block:

  # need to use 'sudo' as we allow privileges just for this command
  # this also ensures we fail if it does not exist
  - name: pull image
    shell: "sudo /usr/bin/podman pull {{ karrot__image }}"
    changed_when: False

  - name: update image
    lineinfile:
      path: /var/www/{{ site }}/www/backend/service.env
      regexp: '^KARROT_IMAGE='
      line: "KARROT_IMAGE={{ karrot__image }}"
    notify:
      - restart