---
#---------------------------------------------------------
# PHP pool
- name: php packages
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: true
  vars:
    packages:
      - "php" 
      - "php-fpm"
  notify:
    - reload php-fpm

- name: allow group read access to home directory
  file:
    path: "/var/www/{{ site }}"
    owner: "{{ site }}"
    group: "{{ site }}"
    mode: "g=rx,o="

- name: allow group read access to home subdirectories
  file:
    path: "/var/www/{{ site }}/{{ item }}"
    state: directory
    owner: "{{ site }}"
    group: "{{ site }}"
    mode: "g=rx,o="
  with_items:
    - www
    - log
    - cert

- name: "Adding user 'www-data' to group '{{ site }}'"
  user:
    name: www-data
    groups: "{{ site }}"
    append: yes

- name: php fpm pool config
  template:
    src: php.j2
    dest: /etc/php/7.3/fpm/pool.d/{{ site }}.conf
  notify:
    - reload php-fpm

- name: nginx php upstream config
  template:
    src: nginx.j2
    # TODO: should be moved to sites-available and then symlinked
    dest: /etc/nginx/sites-enabled/{{ site }}-php-upstream
  notify:
    - reload nginx

- name: nginx sites-enabled symlink
  file:
    src: /etc/nginx/sites-available/{{ site }}
    dest: /etc/nginx/sites-enabled/{{ site }}
    state: link
  notify:
    - reload nginx
