---

- name: reload nginx
  systemd:
    name: nginx
    state: reloaded
    daemon_reload: yes

- name: restart weblate uwsgi
  listen: restart weblate
  systemd:
    name: "{{ site }}"
    state: restarted
    daemon_reload: yes

- name: restart weblate celery
  listen: restart weblate
  systemd:
    name: "{{ site }}-celery.service"
    state: restarted
    daemon_reload: yes
