---

#------------------------------------------------------------------
# nginx config

- name: nginx config
  template:
    src: nginx.j2
    dest: /etc/nginx/sites-available/{{ site }}
  notify:
    - reload nginx

- name: nginx sites-enabled symlink
  file:
    src: /etc/nginx/sites-available/{{ site }}
    dest: /etc/nginx/sites-enabled/{{ site }}
    state: link
  notify:
    - reload nginx

- name: create directories
  become: yes
  become_user: "{{ site }}"
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ static_root }}"

- name: update code
  git:
    repo: https://gitlab.com/yunity/ukuvota.git
    dest: /var/www/{{ site }}/www
    update: yes
    version: master
  become: yes
  become_user: "{{ site }}"

- name: install dependencies
  command: yarn
  args:
    chdir: "/var/www/{{ site }}/www/server/"
  changed_when: False

- name: systemd ukuvota backend service
  template:
    src: ukuvota.service.j2
    dest: /etc/systemd/system/{{ site }}-backend.service

- name: systemd enable ukuvota service
  systemd:
      name: "{{ site }}-backend.service"
      state: started
      enabled: yes
