---
- name: karrot download | setup
  hosts: all
  become: yes
  vars:
    site: karrot-download
    server_name: download.karrot.world
    redirects: []
    public_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPLa2nCA2AZsG8/ZYTRocmaxk07D7O9mGWr0RJf9nlfn karrot deploy 2023-03-17"
  tasks:
    - name: check ansible version
      include_role:
        name: check-ansible-version

    - name: basic-site
      include_role:
        name: basic-site
      tags:
        - nginx
        - cert
        - public key

    - name: nginx config
      template:
        src: nginx.j2
        dest: /etc/nginx/sites-available/{{ site }}
      tags:
        - nginx
