---
- name: karrot dev | deploy
  hosts: all
  become: yes
  vars_files:
    - vars.yml
  tasks:

    - name: check ansible version
      include_role:
        name: check-ansible-version

    - name: deploy
      include_role:
        name: karrot-frontend-deploy
      vars:
        site: karrot-dev
        # detirmines the image tag we use
        # can use --extra-vars to pass a different value
        karrot_frontend__version: latest
