---
- name: karrot dev | deploy
  hosts: all
  become: yes
  tasks:

    - name: check ansible version
      include_role:
        name: check-ansible-version

    - name: deploy
      include_role:
        name: karrot-backend-deploy
      vars:
        site: karrot-dev
        # detirmines the image tag we use
        # can use --extra-vars to pass a different value
        karrot__version: latest
