---
- name: karrot dev | setup
  hosts: all
  become: yes
  vars_files:
    - secrets.vars.yml
  vars:
    site: karrot-dev
    site_name: dev.karrot.world
    server_name: dev.karrot.world
    uploads_directory: uploads
    branch: master
    redirects:
      - dev.foodsaving.world
      - devdev.foodsaving.world
      - karrot-dev.foodsaving.world
      - dev.yunity.org
      - mvp-proposal.yunity.org
    extra_dns:
      # for branch deployments
      # to apply: ansible-playbook playbooks/karrot-dev/setup.playbook.yml --tags cert
      # long term
      - circleci-update-dependencies.dev.karrot.world
      # temporary
      - update-change-service-worker-caching.dev.karrot.world
    postgresql_database: fstool-dev
    postgresql_user: fstool-dev
    sparkpost_relay_domain: replies.dev.karrot.world
    postal_api_url: "https://postal.karrot.world"
    postal_webhook_public_key: "MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDXnPQvaIqgtlUn/bfGX/4rhhuWohuw5j0rqlgFvU2ANDBhsRzoQEabJ1bLAIOP63sWbgIGxvb9xRcorSm16kmBTWHSemsYkHQ/ib71trtMDvhyqW+HdiG5krHeok/LIdLKhl3/aGEsxO+WjMjHKoKBbBnuwkVC4cXK3oTPSfTFtwIDAQAB"
    from_email_address: noreply@dev.karrot.world
    postgresql_socket_auth: false
    csp_report_uri: "https://sentry.io/api/1249808/security/?sentry_key=5c7a0f337fbe4e9ca8626f0e203a2569&sentry_environment=development"
    csp_report_only: false

  tasks:
    - name: check ansible version
      include_role:
        name: check-ansible-version

    - name: server-base
      include_role:
        name: server-base

    - name: basic-site
      include_role:
        name: basic-site
      tags:
        - nginx
        - cert

    - name: postgresql-db
      include_role:
        name: postgresql-db

    - name: karrot-backend
      include_role:
        name: karrot-backend
      vars:
        static_root: /home/deploy/karrot-frontend/master
        apk: /home/deploy/karrot-app/master/app.apk
        redis_db: 4
        influxdb_database: karrot-dev
        workers: 4
        additional_allowed_hosts:
          - .dev.karrot.world
        csrf_trusted_origins:
          - .karrot.world
          - .dev.karrot.world
        deploy_public_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDCFPeaQC8udTj1ydWTlKQ2H5qePbVR+9rlUizGn9R58Mjteiijp/oNldDRzR0AHQjTEbufKkKcGsoT+oNWzsfUE+YWZB/06woKwsjhQPNBN/cvbOnwnFBwQsn/8S/nU7sIb4+2CGPC8VWhkUAJUuYZkbN8nPPx6B9Aj48Hq5oBpZNw2K1fornBXntgRA+zTL5NYBiFucKdwnt+yw49tJYP3OuBD+TTNk5Rg7HEXqcMDoK9hdZIk7PIDLGyg0qGcbaaPziP3zwGBfCRH58xVJQ8DwRoQLnsjj6HzW+nx04P0bhbqSKIRUd8b1HyyOxBwsDUgl94yn3eaR5qB/OfN0Xs4lTDX3pskXQuW8z7/z5xni9Gf+lYI/MImGpddS64GxrfrMgIr9sgPgaPkuLQ8eNOUphkv+gOHvGSeHH9mWRlreIlp9I47vb1petUBv3ac9LEN416lfY8j/Zpl8S8BE2ld0UYT1pa2Dypb/lZ8NZqnE0tZjqJhEWXLH79wsPre3voQElX6/RAnhfu7/Gn0KbrHz7psUtLlRrQflyTCv00G7OaMIUbH3PPRMGGcxuW2RpfmxNIGJ3Iz8DxkaeE5jYNTMXGwUgeQ2HlM8Q5C3UA1xQM5+EhU7T63i3RHeGrPseFT1zQ/9xLG+IyT2t88FM3FcbZBFfxysAtuQ0fAD1OkQ== yunity circleci"
        karrot_branch_deployment_enabled: true
        karrot_branch_deployment_server_name: '~^(?<branch>.+)\.dev\.karrot\.world$'
        karrot_branch_deployment_root: '/home/deploy/karrot-frontend/branches/$branch'
      tags:
        - nginx
        - dependencies

    - name: karrot-backend-deploy
      include_role:
        name: karrot-backend-deploy
