---
- name: karrot dev | setup
  hosts: all
  become: yes
  vars_files:
    - secrets.vars.yml
  vars:
    site: karrot-dev
    site_name: dev.karrot.world
    server_name: dev.karrot.world
    uploads_directory: uploads
    branch: master
    redirects:
      - dev.foodsaving.world
      - devdev.foodsaving.world
      - karrot-dev.foodsaving.world
      - dev.yunity.org
      - mvp-proposal.yunity.org
    extra_dns:
      # for branch deployments
      # to apply: ansible-playbook playbooks/karrot-dev/setup.playbook.yml --tags cert
      # long term
      - circleci-update-dependencies.dev.karrot.world
      # temporary
      - add-video-calls.dev.karrot.world
    postgresql_database: fstool-dev
    postgresql_user: fstool-dev
    sparkpost_relay_domain: replies.dev.karrot.world
    postal_api_url: "https://postal.karrot.world"
    postal_webhook_public_key: "MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDpRMSyj8jfBVRTZvBi+yNNm+ORjdz80G+7YsCC7mrzwPFEBlAysU0ToRB2E982EVgH9mQHmRo3bkzhEAaULROCb9RZYuEJgCHZC6vuEMN+TCpfwz8GCP3YsCciKaEUDGjfhlxSkYijkYKpmpRaZGJRgoGVECuDGsRopfDXZjm0eQIDAQAB"
    from_email_address: noreply@dev.karrot.world
    postgresql_socket_auth: false
    csp_report_uri: "https://o68809.ingest.sentry.io/api/1249808/security/?sentry_key=5c7a0f337fbe4e9ca8626f0e203a2569&sentry_environment=karrot-dev"
    csp_report_only: false

  tasks:
    - name: check ansible version
      include_role:
        name: check-ansible-version

    - name: server-base
      include_role:
        name: server-base
      tags:
        - redis_conf

    - name: basic-site
      include_role:
        name: basic-site
      tags:
        - nginx
        - cert

    - name: postgresql-db
      include_role:
        name: postgresql-db
      vars:
        postgresql_socket_auth: true
        postgresql_extensions:
          - citext
          - btree_gist
      tags:
        - pg_extensions

    - name: karrot-backend
      include_role:
        name: karrot-backend
      vars:
        static_root: /var/www/karrot-dev/www/frontend/dev/current
        apk: /home/deploy/karrot-app/master/app.apk
        redis_db: 4
        influxdb_database: karrot-dev
        karrot__worker_count: 2
        # https://docs.djangoproject.com/en/4.2/ref/settings/#allowed-hosts
        additional_allowed_hosts:
          - .dev.karrot.world
        # https://docs.djangoproject.com/en/4.2/ref/settings/#csrf-trusted-origins
        csrf_trusted_origins:
          - "https://*.karrot.world"
          - "https://*.dev.karrot.world"
        deploy_public_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPLa2nCA2AZsG8/ZYTRocmaxk07D7O9mGWr0RJf9nlfn karrot deploy 2023-03-17"
        karrot_branch_deployment_enabled: true
        karrot_branch_deployment_server_name: '~^(?<branch>.+)\.dev\.karrot\.world$'
        karrot_branch_deployment_root: '/home/deploy/karrot-frontend/branches/$branch'
        # not ready yet, as currently have a bunch of things that haven't been deployed there...
        #karrot_branch_deployment_root: '/var/www/karrot-dev/www/frontend/$branch/current'
        #geoipupdate__account_id: <put in secrets.vars.yml>
        #geoipupdate__license_key: <put in secrets.vars.yml>
        forum_banner_topic_id: '930'
        forum_discussions_feed: 'latest.json'
        vapid_admin_email: "info@karrot.world"
        vapid_public_key: "BMCBmm6SihKZV0rb4_YqMIzKpX-2YRWiP5Ro7pSGJD0flq9jyzNPaKXNDOfqY7ZUAIOtt9-cZdDcty4APp3isB8"
        # vapid_private_key: <put in secrets.vars.yml>
        meet_livekit_endpoint: wss://livekit.karrot.world
        meet_livekit_api_key: karrot-dev
        # meet_livekit_api_secret: <put in secrets.vars.yml>
      tags:
        - nginx
        - dependencies
        - geoipupdate
        - django settings
        - deploy public key

    - name: karrot-backend-deploy
      include_role:
        name: karrot-backend-deploy
