---

- name: install nginx
  apt:
    name: nginx-extras
    state: present
    update_cache: true

- name: setup basic nginx config
  template:
    dest: /etc/nginx/nginx.conf
    src: nginx.conf.j2

- name: copy nginx default site
  copy:
    dest: /etc/nginx/sites-available/default
    src: default
  notify:
    - reload nginx

- name: enable nginx default site
  file:
    src: /etc/nginx/sites-available/default
    dest: /etc/nginx/sites-enabled/default
    state: link
  notify:
    - reload nginx

- name: copy letsencrypt intermediate cert
  get_url:
    url: https://letsencrypt.org/certs/lets-encrypt-x3-cross-signed.pem.txt
    dest: /etc/nginx/conf.d/lets-encrypt-x3-cross-signed.pem

- name: copy dhparams
  copy:
    dest: /etc/nginx/conf.d/dhparams.pem
    src: dhparams.pem
