---

- name: add influxdb apt key
  apt_key:
    url: https://repos.influxdata.com/influxdb.key
    state: present

- name: add influxdb repository
  apt_repository:
    repo: deb https://repos.influxdata.com/debian bullseye stable
    state: present

- name: install influxdb
  apt:
    name: influxdb
    state: latest
    update_cache: true

- name: enable/start influxdb
  systemd:
    name: influxdb
    state: started
    enabled: yes

- name: install influxdb python lib
  pip:
    name: influxdb
    state: present

- name: create influxdb database
  influxdb_database:
    database_name: "{{ influxdb_database }}"
    hostname: 127.0.0.1
    username: ""
    password: ""

- name: create grafana postgres user
  postgresql_user:
    name: "{{ site }}-grafana"
    password: grafana
    db: "{{ postgresql_database }}"
    priv: CONNECT/group_names:SELECT
    encrypted: yes
    state: present
  become: true
  become_user: postgres