---

- name: add influxdb apt key
  apt_key:
    url: https://repos.influxdata.com/influxdb.key
    state: present

- name: add influxdb repository
  apt_repository:
    repo: deb https://repos.influxdata.com/debian buster stable
    state: present

- name: install influxdb
  apt:
    # there is an old influxdb in debian repo
    # we want new shiny one, for which I had to specify the version
    name: influxdb=1.7*
    state: present
    update_cache: true

- name: enable/start influxdb
  systemd:
    name: influxdb
    state: started
    enabled: yes

- name: install influxdb python lib
  pip:
    name: influxdb
    state: present

- name: create influxdb database
  influxdb_database:
    database_name: "{{ influxdb_database }}"
    hostname: 127.0.0.1
    login_username: "{{ influxdb_admin_username }}"
    login_password: "{{ influxdb_admin_password }}"

- name: create influxdb user
  influxdb_user:
    user_name: "{{ influxdb_database }}"
    user_password: "{{ influxdb_password }}"
    login_username: "{{ influxdb_admin_username }}"
    login_password: "{{ influxdb_admin_password }}"
    grants:
      - database: "{{ influxdb_database }} "
        privilege: 'ALL'

- name: create grafana postgres user
  postgresql_user:
    name: "{{ site }}-grafana"
    password: grafana
    db: "{{ postgresql_database }}"
    priv: CONNECT/group_names:SELECT
    encrypted: yes
    state: present
  become: true
  become_user: postgres