- name: backup direcory
  file:
    path: /root/backup
    state: directory
  become: yes

- name: password file
  copy:
    content: "{{ restic_password }}"
    dest: /root/backup/password-file-{{ name }}
  become: yes

- name: backup script
  template:
    src: run.sh.j2
    dest: "/root/backup/run-{{ name }}.sh"
    mode: u=rwx

- name: create backup cronjob
  cron:
    name: "{{ name }} restic backup"
    minute: "0"
    hour: "4"
    job: "/root/backup/run-{{ name }}.sh | /usr/bin/logger -t resticbackup"
