---

- name: restart livekit
  systemd:
    name: '{{ livekit__service_name }}'
    state: restarted
    daemon_reload: yes

- name: reload nginx
  systemd:
    name: nginx
    state: reloaded
    daemon_reload: yes
