---
- name: foodsharing Taiwan | setup
  hosts: all
  become: yes
  vars_files:
    - secrets.vars.yml
  vars:
    site: foodsharing-taiwan
    server_name: app.foodsharing.tw
    uploads_directory: uploads
    branch: production
    redirects:
      - tw.foodsaving.world
      - karrot.foodsharing.tw
    postgresql_database: fstaiwan
    postgresql_user: fstaiwan
    sparkpost_relay_domain: replies.app.foodsharing.tw
    postgresql_socket_auth: false
  tasks:

    - name: check ansible version
      include_role:
        name: check-ansible-version

    - name: server-base
      include_role:
        name: server-base

    - name: basic-site
      include_role:
        name: basic-site
      tags:
        - nginx

    - name: postgresql-db
      include_role:
        name: postgresql-db
      vars:
        # backup_host: tor-relay.chandi.it
        # backup_user: tiltec
        # backup_path: ~/fstaiwan-backup/
        # backup_password set by secrets.vars.yml

    - name: karrot-backend
      include_role:
        name: karrot-backend
      vars:
        site_name: Foodsharing Taiwan
        static_root: /home/deploy/karrot-frontend/release
        from_email_address: noreply@app.foodsharing.tw
        redis_db: 3
        workers: 4
        csrf_trusted_origins:
          - .foodsharing.tw
        deploy_public_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDCFPeaQC8udTj1ydWTlKQ2H5qePbVR+9rlUizGn9R58Mjteiijp/oNldDRzR0AHQjTEbufKkKcGsoT+oNWzsfUE+YWZB/06woKwsjhQPNBN/cvbOnwnFBwQsn/8S/nU7sIb4+2CGPC8VWhkUAJUuYZkbN8nPPx6B9Aj48Hq5oBpZNw2K1fornBXntgRA+zTL5NYBiFucKdwnt+yw49tJYP3OuBD+TTNk5Rg7HEXqcMDoK9hdZIk7PIDLGyg0qGcbaaPziP3zwGBfCRH58xVJQ8DwRoQLnsjj6HzW+nx04P0bhbqSKIRUd8b1HyyOxBwsDUgl94yn3eaR5qB/OfN0Xs4lTDX3pskXQuW8z7/z5xni9Gf+lYI/MImGpddS64GxrfrMgIr9sgPgaPkuLQ8eNOUphkv+gOHvGSeHH9mWRlreIlp9I47vb1petUBv3ac9LEN416lfY8j/Zpl8S8BE2ld0UYT1pa2Dypb/lZ8NZqnE0tZjqJhEWXLH79wsPre3voQElX6/RAnhfu7/Gn0KbrHz7psUtLlRrQflyTCv00G7OaMIUbH3PPRMGGcxuW2RpfmxNIGJ3Iz8DxkaeE5jYNTMXGwUgeQ2HlM8Q5C3UA1xQM5+EhU7T63i3RHeGrPseFT1zQ/9xLG+IyT2t88FM3FcbZBFfxysAtuQ0fAD1OkQ== yunity circleci"
        influxdb_database: fstaiwan
        # borgbackup remote repository is unused
        borgbackup_server_user: tiltec
        borgbackup_client_backup_server: tor-relay.chandi.it
        postal_api_url: "https://postal.karrot.world"
      tags:
        - nginx

    - name: karrot-backend-deploy
      include_role:
        name: karrot-backend-deploy
