---
- name: PostgreSQL packages are installed
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - postgresql
    - python3-psycopg2

- name: Start PostgreSQL and enable at boot
  systemd:
    name: postgresql
    enabled: yes
    state: started
    daemon_reload: yes

- name: configure postgres (as recommended by Discourse)
  postgresql_set:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  loop:
    - name: shared_buffers
      value: 256MB
    - name: work_mem
      value: 10MB
    - name: synchronous_commit
      value: "off"
    - name: default_text_search_config
      value: "pg_catalog.english"
    - name: max_wal_senders
      value: 0
    - name: wal_level
      value: minimal      
  register: postgresql_config
  become: true
  become_user: postgres  

- name: allow md5 login via postgres socket
  when: postgresql_socket_auth
  postgresql_pg_hba:
    dest: /etc/postgresql/11/main/pg_hba.conf
    contype: local
    databases: "{{ postgresql_database }}"
    users: "{{ postgresql_user }}"
    method: md5
  register: postgresql_hba_config
  become: true
  become_user: postgres  

- name: restart postgresql
  when: postgresql_config.changed
  systemd:
    name: postgresql
    state: restarted

- name: reload postgresql
  when: postgresql_hba_config.changed
  systemd:
    name: postgresql
    state: reloaded

- name: role
  postgresql_user:
    name: "{{ postgresql_user }}"
    password: "{{ postgresql_password }}"
    encrypted: yes
    state: present
    role_attr_flags: CREATEDB
  become: true
  become_user: postgres

- name: database
  postgresql_db:
    name: "{{ postgresql_database }}"
    encoding: UTF-8
    template: template0
    state: present
    owner: "{{ postgresql_user }}"
  become: true
  become_user: postgres

- name: add extensions to application postgres database
  postgresql_ext:
    db: "{{ postgresql_database }}"
    name: "{{ item }}"
  with_items: "{{ postgresql_extensions | default([]) }}"
  become: true
  become_user: postgres
  tags:
    - pg_extensions

- name: adjust owner of schema public
  postgresql_schema:
    database: "{{ postgresql_database }}"
    name: public
    owner: "{{ postgresql_user }}"
  become: true
  become_user: postgres

- name: create backup directory
  file:
    path: "/var/www/{{ site }}/backup/archive"
    state: directory
    owner: "{{ site }}"
    group: "{{ site }}"

- name: create pgpass file for backup script
  copy:
    dest: /var/www/{{ site }}/.pgpass
    content: "localhost:5432:{{ postgresql_database }}:{{ postgresql_user }}:{{ postgresql_password }}\n"
    owner: "{{ site }}"
    group: "{{ site }}"
    mode: "600"

- name: install backup script
  template:
    src: backup.sh.j2
    dest: /var/www/{{ site }}/backup/backup.postgres.sh
    owner: "{{ site }}"
    group: "{{ site }}"
    mode: "770"

- when: backup_password is defined
  block:
  - name: setup backup password file
    copy:
      dest: "/var/www/{{ site }}/backup/backup.key"
      content: "{{ backup_password }}"
      mode: "600"
      owner: "{{ site }}"

  - name: create backup cronjob
    cron:
      name: "{{ site }} | backup"
      minute: "0"
      hour: "3"
      job: "cd /var/www/{{ site }}/backup/ && ./backup.postgres.sh > /dev/null"
      user: "{{ site }}"

- when: backup_host is defined
  block:
  - name: generate ssh key for site user
    user:
      name: "{{ site }}"
      generate_ssh_key: True
      ssh_key_type: ed25519
    notify:
      - print ssh key

  - name: "add backup server to known hosts"
    copy:
      dest: "/var/www/{{ site }}/.ssh/backup_known_hosts"
      content: "{{ lookup('pipe', 'ssh-keyscan {{ backup_host }}') }}\n"      

