---
- name: PostgreSQL packages are installed
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - postgresql
    - python-psycopg2

- name: Start PostgreSQL and enable at boot
  systemd:
    name: postgresql
    enabled: yes
    state: started
    daemon_reload: yes

- name: Copy postgres config
  copy:
    dest: /etc/postgresql/9.6/main/postgresql.conf
    src: postgresql.conf
  register: postgresql_config

- name: allow md5 login via postgres socket
  lineinfile:
    path: /etc/postgresql/9.6/main/pg_hba.conf
    line: "local {{ postgresql_database }} {{ postgresql_user }} md5"
    insertafter: '# "local" is for Unix domain socket connections only'
  when: postgresql_socket_auth
  register: postgresql_hba_config

- name: restart postgresql
  when: postgresql_config.changed
  systemd:
    name: postgresql
    state: restarted

- name: reload postgresql
  when: postgresql_hba_config.changed
  systemd:
    name: postgresql
    state: reloaded

- name: role
  postgresql_user:
    name: "{{ postgresql_user }}"
    password: "{{ postgresql_password }}"
    encrypted: yes
    state: present
    role_attr_flags: CREATEDB
  become: true
  become_user: postgres

- name: database
  postgresql_db:
    name: "{{ postgresql_database }}"
    encoding: UTF-8
    template: template0
    state: present
    owner: "{{ postgresql_user }}"
  become: true
  become_user: postgres

- name: add extensions to application postgres database
  postgresql_ext:
    db: "{{ postgresql_database }}"
    name: "{{ item }}"
  with_items: "{{ postgresql_extensions | default([]) }}"
  become: true
  become_user: postgres

- name: adjust owner of schema public
  postgresql_schema:
    database: "{{ postgresql_database }}"
    name: public
    owner: "{{ postgresql_user }}"
  become: true
  become_user: postgres

- when: backup_host is defined
  block:
  - name: generate ssh key for site user
    user:
      name: "{{ site }}"
      generate_ssh_key: True
      ssh_key_type: ed25519
    notify:
      - print ssh key

  - name: create backup directory
    file:
      path: "/var/www/{{ site }}/backup/archive"
      state: directory
      owner: "{{ site }}"
      group: "{{ site }}"

  - name: create pgpass file for backup script
    copy:
      dest: /var/www/{{ site }}/.pgpass
      content: "localhost:5432:{{ postgresql_database }}:{{ postgresql_user }}:{{ postgresql_password }}\n"
      owner: "{{ site }}"
      group: "{{ site }}"
      mode: "600"

  - name: install backup script
    template:
      src: backup.sh.j2
      dest: /var/www/{{ site }}/backup/backup.postgres.sh
      owner: "{{ site }}"
      group: "{{ site }}"
      mode: "770"

  - name: "add backup server to known hosts"
    copy:
      dest: "/var/www/{{ site }}/.ssh/backup_known_hosts"
      content: "{{ lookup('pipe', 'ssh-keyscan {{ backup_host }}') }}\n"

  - name: setup backup password file
    copy:
      dest: "/var/www/{{ site }}/backup/backup.key"
      content: "{{ backup_password }}"
      mode: "600"
      owner: "{{ site }}"

  - name: create backup cronjob
    cron:
      name: "{{ site }} | backup"
      minute: "0"
      hour: "3"
      job: "cd /var/www/{{ site }}/backup/ && ./backup.postgres.sh > /dev/null"
      user: "{{ site }}"
