---
- name: community.karrot.world | update
  hosts: all
  become: yes
  vars:
    site: foodsaving-community
    discourse_location: "/var/www/{{ site }}/docker"

  tasks:
    - name: check ansible version
      include_role:
        name: check-ansible-version

    - name: update-discourse
      include_role:
        name: update-discourse
