---
- name: yuca | setup
  hosts: all
  become: yes
  vars_files:
    - secrets.vars.yml
  tasks:
    - name: restic-backup
      include_role:
        name: restic-backup
      vars:
        name: yuca
        restic_repo: "b2:karrot-backup:"
        restic_password: "{{ restic_password_b2 }}"
        restic_b2_account_id: "{{ restic_b2_account_id_yuca }}"
        restic_b2_account_key: "{{ restic_b2_account_key_yuca }}"
        postgres_databases: 
          - foodsaving-community
          - karrot-world
          - fstool-dev
        folders:
            - /etc
            - /var/www/karrot-dev/www/uploads
            - /var/www/karrot-world/www/uploads
            - /var/www/foodsaving-community/docker/shared/web_only/uploads/default/original

    - name: prometheus node exporter
      include_role:
        name: prometheus

    - name: logrotate
      include_role:
        name: logrotate
      tags:
        - logrotate