---
- name: yuca | setup
  hosts: all
  become: yes
  vars_files:
    - secrets.vars.yml
  tasks:
    - name: restic-backup
      include_role:
        name: restic-backup
      vars:
        name: yuca
        restic_repo: sftp:yuca-backup@cashew.chandi.it:/repo
        restic_password: "{{ restic_password_cashew }}"
        postgres_databases: 
          - foodsaving-community
          - fstaiwan
          - karrot-world
          - fstool-dev
          - kanthaus-nextcloud
        folders:
            - /etc
            - /var/www/kanthaus-nextcloud/nextcloud_data
            - /var/www/kanthaus-nextcloud/www
            - /var/www/karrot-dev/www/uploads
            - /var/www/karrot-world/www/uploads
            - /var/www/foodsharing-taiwan/www/uploads
            - /var/www/foodsaving-community/docker/shared/web_only/uploads/default/original