# check https://github.com/RocketChat/Rocket.Chat/releases for available versions
rocketchat__version: '3.10.5'

rocketchat__service_name: '{{ site }}'
rocketchat__service_description: '{{ site_name }}'

rocketchat__root_url: 'https://{{ server_name }}/'

rocketchat__root: '/var/www/{{ site }}/rocketchat'
rocketchat__latest: '{{ rocketchat__root }}/versions/{{ rocketchat__version }}'
rocketchat__current:  '{{ rocketchat__root }}/current'

rocketchat__user: '{{ site }}'
rocketchat__group: '{{ site }}'

rocketchat__database_name: '{{ site }}'

# will this get shared for instances, seems I can only have one per db instance...
rocketchat__replicaset_name: 'rocketchat'

# must override this for other installations
rocketchat__port: '5000'
