---
- name: kanthaus-online | setup
  hosts: all
  become: yes
  vars:
    site: kanthaus-online-grav
    server_name: kanthaus.online
    redirects: [www.kanthaus.online, grav.kanthaus.online]
  tasks:

    - name: check ansible version
      include_role:
        name: check-ansible-version

    - name: basic-site
      include_role:
        name: basic-site
      tags:
        - nginx
        - cert

    - name: php-fpm-site
      include_role:
        name: php-fpm-site

    - name: kanthaus-online
      include_role:
        name: grav-php-site
