---

- name: restart daphne
  listen: restart app
  systemd:
    name: "{{ site }}-daphne.target"
    state: restarted
    daemon_reload: yes

- name: restart huey
  listen: restart app
  systemd:
    name: "{{ site }}-huey.service"
    state: restarted
    daemon_reload: yes
