---

- name: restart karrot
  listen: restart app
  systemd:
    name: "{{ site }}.service"
    state: restarted
    daemon_reload: yes

- name: restart karrot worker
  listen: restart app
  systemd:
    name: "{{ site }}-worker.service"
    state: restarted
    daemon_reload: yes

- name: reload nginx
  systemd:
    name: nginx
    state: reloaded
    daemon_reload: yes

