---

- name: restart daphne
  listen: restart app
  systemd:
    name: "{{ site }}.target"
    state: restarted
    daemon_reload: yes

- name: restart huey
  listen: restart app
  systemd:
    name: "{{ site }}-huey.service"
    state: restarted
    daemon_reload: yes

- name: reload nginx
  systemd:
    name: nginx
    state: reloaded
    daemon_reload: yes

