livekit__version: "1.5.2"
livekit__download_url: "https://github.com/livekit/livekit/releases/download/v{{ livekit__version }}/livekit_{{ livekit__version }}_linux_amd64.tar.gz"
livekit__root: '/var/www/{{ site }}/www'
livekit__executable: '{{ livekit__root }}/livekit-server'
livekit__configfile: '{{ livekit__root }}/config.yaml'
livekit__user: '{{ site }}'
livekit__group: '{{ site }}'
livekit__service_name: '{{ site }}'
livekit__port: 7880
livekit__webrtc_tcp_port: 7881
livekit__webrtc_port_range_start: 50000
livekit__webrtc_port_range_end: 60000
livekit__turn_server_name: 'turn-{{ server_name }}'
livekit__turn_tls_port: 5349
livekit__api_keys: {}