---
- name: foodsaving worldwide rocketchat | setup
  hosts: all
  become: yes
  vars_files:
    - secrets.vars.yml
  vars:
    site: fsww-rocketchat
    site_name: foodsaving worldwide rocketchat
    server_name: oldchat.karrot.world
    redirects: []
  tasks:
    - name: check ansible version
      include_role:
        name: check-ansible-version

    - name: server-base
      include_role:
        name: server-base
      tags:
        - server-base

    - name: basic-site
      include_role:
        name: basic-site
      tags:
        - nginx
        - cert

    - name: rocketchat
      include_role:
        name: rocketchat
      tags:
        - upgrade
